homeassistant:
  name: Renwick
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  elevation: 196
  temperature_unit: F
  unit_system: imperial
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:
  
zone:
  name: Home
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  icon: mdi:castle
  radius: 500

http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun
      - sensor.time

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

vera:
  vera_controller_url: http://192.168.1.113:3480/
  exclude: [4,5,6]

# Cloud
cloud:
    
mqtt:
    broker: m10.cloudmqtt.com
    port: 20331
    username: !secret mqtt_username
    password: !secret mqtt_password

hue:
  bridges:
    - host: 192.168.1.110
      filename: huebridge.conf

sensor: !include_dir_merge_list partials/sensor
switch: !include_dir_merge_list partials/switch
light: !include_dir_merge_list partials/light
cover: !include_dir_merge_list partials/cover
weblink: !include_dir_named partials/weblink
device_tracker: !include_dir_merge_list partials/device_tracker
group: !include_dir_merge_named partials/group

#group: !include partials/group/views.yaml

automation: !include automations.yaml
script: !include scripts.yaml