homeassistant:
  # Name of the location where Home Assistant is running
  name: Renwick
  # Location required to calculate the time the sun rises and sets
  #latitude: 39.693
  # longitude: -77.740
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 196
  temperature_unit: F
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:
  
zone:
  name: Home
  # latitude: 39.693
  # longitude: -77.740
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  icon: mdi:castle
  radius: 500

http:
  # api_password: 24Turtles
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun
      - sensor.time

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

vera:
  vera_controller_url: http://192.168.1.113:3480/
  exclude: [4,5,6]

# Cloud
cloud:
    
mqtt:
    broker: m10.cloudmqtt.com
    port: 20331
    username: !secret mqtt_username
    password: !secret mqtt_password

hue:
  bridges:
    - host: 192.168.1.110
      filename: huebridge.conf

sensor: !include_dir_merge_list partials/sensor
switch: !include_dir_merge_list partials/switch
light: !include_dir_merge_list partials/light
cover: !include_dir_merge_list partials/cover
weblink: !include_dir_named partials/weblink
device_tracker: !include_dir_merge_list partials/device_tracker

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml