# https://home-assistant.io/cookbook/google_maps_card/
- platform: generic
  name: Tyler
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pwbwmuqz_g5.attributes.latitude }},{{ states.device_tracker.pwbwmuqz_g5.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.pwbwmuqz_g5.attributes.latitude }},{{ states.device_tracker.pwbwmuqz_g5.attributes.longitude }}
  limit_refetch_to_url_change: true