# https://home-assistant.io/components/sensor.sabnzbd/
# would like to eventually graph some of the data @ https://home-assistant.io/components/sensor.statistics/
- platform: sabnzbd
  host: 192.168.1.121
  port: 8080
  api_key: !secret sabnzbd_api_key
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'
    - 'queue_count'