# https://home-assistant.io/components/sensor.systemmonitor/
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use