# https://home-assistant.io/components/sensor.systemmonitor/
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /home/tyler/Movies
    - type: disk_use_percent
      arg: /home/tyler/TV
    - type: disk_use_percent
      arg: /media/backupDrive1
    - type: disk_use_percent
      arg: /media/backupDrive2
    - type: disk_use_percent
      arg: /media/backupDrive3
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use